<?php
namespace App\Service;

use App\Entity\Project;

class JamboClientGenerator
{
    /**
     * Generates a typed lib/jambo.ts client from the project's real schema.
     */
    public function generate(Project $project, string $jamboApiUrl, string $projectUuid): string
    {
        $lines = [];
        $lines[] = "// Auto-generated by Jambo Workbench — do not edit manually";
        $lines[] = "const JAMBO_URL = '{$jamboApiUrl}';";
        $lines[] = "const PROJECT   = '{$projectUuid}';";
        $lines[] = '';

        foreach ($project->collections as $col) {
            if (method_exists($col, 'isDeleted') && $col->isDeleted()) {
                continue;
            }

            $typeName = $this->toPascalCase($col->slug ?? $col->name ?? 'Item');
            $lines[] = "export interface {$typeName} {";
            $lines[] = "  uuid: string;";
            $lines[] = "  locale: string;";
            $lines[] = "  status: 'draft' | 'published';";

            foreach ($col->fields as $field) {
                if (method_exists($field, 'isDeleted') && $field->isDeleted()) {
                    continue;
                }
                $tsType = $this->mapType($field->type);
                $optional = $field->isRequired ? '' : '?';
                $lines[] = "  {$field->slug}{$optional}: {$tsType};";
            }

            $lines[] = "  created_at: string;";
            $lines[] = "  updated_at: string;";
            $lines[] = '}';
            $lines[] = '';

            $fnName = 'get' . $this->toPascalCase($col->slug ?? $col->name ?? 'items');
            $slug   = $col->slug ?? '';
            $lines[] = "export async function {$fnName}(): Promise<{$typeName}[]> {";
            $lines[] = "  const res = await fetch(`\${JAMBO_URL}/api/\${PROJECT}/collections/{$slug}`);";
            $lines[] = "  const json = await res.json();";
            $lines[] = "  return json.data ?? json;";
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    private function mapType(string $phpType): string
    {
        return match($phpType) {
            'number', 'decimal'              => 'number',
            'boolean', 'checkbox'            => 'boolean',
            'json', 'array', 'repeater'      => 'Record<string, unknown>',
            'media', 'relation'              => 'string | string[]',
            default                          => 'string',
        };
    }

    private function toPascalCase(string $slug): string
    {
        return str_replace(' ', '', ucwords(str_replace(['-', '_'], ' ', $slug)));
    }
}
