<?php
// src/Service/ZipExportService.php
namespace App\Service;

use App\Entity\WorkbenchProject;
use App\Workbench\Templates\BaseTemplate;

class ZipExportService
{
    /** @param BaseTemplate[] $templates */
    public function __construct(private readonly iterable $templates) {}

    /**
     * Builds and returns ZIP archive bytes for the given WorkbenchProject.
     * The ZIP contains: all generated files + Dockerfile + docker-compose + .env.example + GitHub Actions workflow.
     */
    public function export(WorkbenchProject $project): string
    {
        $template = $this->findTemplate($project->framework);

        $tmpFile = tempnam(sys_get_temp_dir(), 'jambo_export_') . '.zip';
        $zip     = new \ZipArchive();
        $zip->open($tmpFile, \ZipArchive::CREATE | \ZipArchive::OVERWRITE);

        // 1. Generated app files
        foreach ($project->files as $path => $content) {
            $zip->addFromString($path, $content);
        }

        // 2. Infrastructure files
        $zip->addFromString('Dockerfile',            $template?->getDockerfile() ?? $this->defaultDockerfile());
        $zip->addFromString('docker-compose.yml',    $this->buildDockerCompose($project));
        $zip->addFromString('.env.example',          $this->buildEnvExample());
        $zip->addFromString('.gitignore',            $this->buildGitignore($project->framework));
        $zip->addFromString('.github/workflows/deploy.yml', $this->buildGithubActions($project, $template));

        $zip->close();

        $bytes = (string) file_get_contents($tmpFile);
        unlink($tmpFile);

        return $bytes;
    }

    public function suggestedFilename(WorkbenchProject $project): string
    {
        $slug = strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $project->name) ?? 'app');
        return "{$slug}-{$project->framework}.zip";
    }

    private function findTemplate(string $framework): ?BaseTemplate
    {
        foreach ($this->templates as $template) {
            if ($template->getId() === $framework) return $template;
        }
        return null;
    }

    private function buildDockerCompose(WorkbenchProject $project): string
    {
        $name = strtolower(preg_replace('/[^a-z0-9]+/', '-', $project->name) ?? 'app');
        return <<<YAML
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    container_name: {$name}

networks:
  default:
    name: {$name}_network
YAML;
    }

    private function buildEnvExample(): string
    {
        return <<<'ENV'
# Jambo CMS API — generated by Jambo Workbench
JAMBO_API_URL=https://your-jambo-cms.example.com
JAMBO_PROJECT_UUID=your-project-uuid-here

# Next.js (rename to NEXT_PUBLIC_* for client-side access)
NEXT_PUBLIC_JAMBO_API_URL=https://your-jambo-cms.example.com
NEXT_PUBLIC_JAMBO_PROJECT_UUID=your-project-uuid-here

# Production
NODE_ENV=production
PORT=3000
ENV;
    }

    private function buildGitignore(string $framework): string
    {
        $base = "node_modules/\n.env\n.env.local\n*.log\n";
        return match($framework) {
            'nextjs'    => $base . ".next/\nout/\n",
            'nuxt'      => $base . ".nuxt/\n.output/\n",
            'astro'     => $base . "dist/\n",
            'sveltekit' => $base . "build/\n.svelte-kit/\n",
            default     => $base,
        };
    }

    private function buildGithubActions(WorkbenchProject $project, ?BaseTemplate $template): string
    {
        $name       = strtolower(preg_replace('/[^a-z0-9]+/', '-', $project->name) ?? 'app');
        $buildCmd   = $template?->getBuildCommand() ?? 'npm run build';
        $installCmd = $template?->getInstallCommand() ?? 'npm install --legacy-peer-deps';

        return <<<YAML
name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: {$installCmd}

      - name: Build
        run: {$buildCmd}
        env:
          JAMBO_API_URL: \${{ secrets.JAMBO_API_URL }}
          JAMBO_PROJECT_UUID: \${{ secrets.JAMBO_PROJECT_UUID }}
          NEXT_PUBLIC_JAMBO_API_URL: \${{ secrets.JAMBO_API_URL }}
          NEXT_PUBLIC_JAMBO_PROJECT_UUID: \${{ secrets.JAMBO_PROJECT_UUID }}

      - name: Build Docker image
        run: docker build -t {$name}:\${{ github.sha }} .

      - name: Deploy
        run: echo "Add your deploy step here (Docker push, SSH, etc.)"
YAML;
    }

    private function defaultDockerfile(): string
    {
        return <<<'DOCKERFILE'
FROM node:20-alpine
WORKDIR /app
COPY package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["npm", "start"]
DOCKERFILE;
    }
}
