framework:
    rate_limiter:
        login_limiter:
            policy: sliding_window
            limit: 5
            interval: '60 seconds'
        register_limiter:
            policy: sliding_window
            limit: 3
            interval: '60 seconds'
        password_reset_limiter:
            policy: sliding_window
            limit: 3
            interval: '60 seconds'
        mcp_limiter:
            policy: sliding_window
            limit: 60
            interval: '60 seconds'
        captcha:
            policy: sliding_window
            limit: 10
            interval: '60 seconds'
        project_email:
            policy: sliding_window
            limit: 3
            interval: '60 seconds'
        project_email_admin:
            policy: sliding_window
            limit: 30
            interval: '60 seconds'
