security:
    password_hashers:
        App\Entity\User:
            algorithm: auto
        App\Entity\EndUser:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        end_user_provider:
            entity:
                class: App\Entity\EndUser
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false

        end_user:
            pattern: ^/api/[\w-]{36}/auth/(logout|refresh|me)
            stateless: true
            provider: end_user_provider
            custom_authenticators:
                - App\Security\EndUserJwtAuthenticator

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: email
                password_parameter: password
                enable_csrf: true
            login_throttling:
                max_attempts: 5
                interval: '60 seconds'
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/public-api, roles: PUBLIC_ACCESS }
        - { path: '^/api/[\w-]{36}/auth/(register|login|forgot-password|reset-password)', roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: ROLE_USER }
