<?php
// src/Workbench/Templates/NextjsTemplate.php
namespace App\Workbench\Templates;

class NextjsTemplate extends BaseTemplate
{
    public function getId(): string { return 'nextjs'; }
    public function getLabel(): string { return 'Next.js 14'; }
    public function getDevCommand(): string { return 'npm run dev'; }

    public function getStarterFiles(string $jamboApiUrl, string $projectUuid, array $collections): array
    {
        return [
            'package.json' => json_encode([
                'name' => 'jambo-app',
                'version' => '0.1.0',
                'private' => true,
                'scripts' => ['dev' => 'next dev', 'build' => 'next build', 'start' => 'next start'],
                'dependencies' => [
                    'next' => '^14.0.0',
                    'react' => '^18.0.0',
                    'react-dom' => '^18.0.0',
                ],
                'devDependencies' => [
                    'typescript' => '^5.0.0',
                    '@types/node' => '^20.0.0',
                    '@types/react' => '^18.0.0',
                ],
            ], JSON_PRETTY_PRINT),

            'next.config.ts' => "import type { NextConfig } from 'next';\n\nconst config: NextConfig = {};\nexport default config;\n",

            'tsconfig.json' => json_encode([
                'compilerOptions' => [
                    'target' => 'es2017', 'lib' => ['dom', 'dom.iterable', 'esnext'],
                    'allowJs' => true, 'skipLibCheck' => true, 'strict' => true,
                    'noEmit' => true, 'esModuleInterop' => true, 'module' => 'esnext',
                    'moduleResolution' => 'bundler', 'resolveJsonModule' => true,
                    'isolatedModules' => true, 'jsx' => 'preserve', 'incremental' => true,
                    'plugins' => [['name' => 'next']],
                    'paths' => ['@/*' => ['./*']],
                ],
                'include' => ['next-env.d.ts', '**/*.ts', '**/*.tsx', '.next/types/**/*.ts'],
                'exclude' => ['node_modules'],
            ], JSON_PRETTY_PRINT),

            '.env.local' => "NEXT_PUBLIC_JAMBO_API_URL={$jamboApiUrl}\nNEXT_PUBLIC_JAMBO_PROJECT_UUID={$projectUuid}\n",

            'lib/jambo.ts' => $this->generateJamboClient($collections),

            'app/layout.tsx' => <<<'TSX'
import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Jambo App', description: 'Generated by Jambo Workbench' };
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body>{children}</body></html>;
}
TSX,

            'app/page.tsx' => <<<'TSX'
export default function Home() {
  return <main><h1>Welcome to your Jambo App</h1><p>Start chatting with the AI to generate your pages.</p></main>;
}
TSX,
        ];
    }

    /** @param array<array{name:string,slug:string,fields:array<array{name:string,slug:string,type:string}>}> $collections */
    private function generateJamboClient(array $collections): string
    {
        $lines = [];
        $lines[] = "const JAMBO_URL = process.env.NEXT_PUBLIC_JAMBO_API_URL ?? '';";
        $lines[] = "const PROJECT   = process.env.NEXT_PUBLIC_JAMBO_PROJECT_UUID ?? '';";
        $lines[] = '';

        foreach ($collections as $col) {
            $typeName = ucfirst($col['slug'] ?? $col['name'] ?? 'Item');
            $lines[] = "export interface {$typeName} {";
            $lines[] = "  uuid: string;";
            $lines[] = "  locale: string;";
            $lines[] = "  status: 'draft' | 'published';";
            foreach ($col['fields'] ?? [] as $field) {
                $tsType = match($field['type']) {
                    'number', 'decimal' => 'number',
                    'boolean', 'checkbox' => 'boolean',
                    'json', 'array', 'repeater' => 'Record<string, unknown>',
                    'media', 'relation' => 'string | string[]',
                    default => 'string',
                };
                $optional = ($field['isRequired'] ?? false) ? '' : '?';
                $lines[] = "  {$field['slug']}{$optional}: {$tsType};";
            }
            $lines[] = "  created_at: string;";
            $lines[] = "  updated_at: string;";
            $lines[] = '}';
            $lines[] = '';

            $fnName = 'get' . ucfirst($col['slug'] ?? $col['name'] ?? 'items');
            $lines[] = "export async function {$fnName}(): Promise<{$typeName}[]> {";
            $lines[] = "  const res = await fetch(`\${JAMBO_URL}/api/\${PROJECT}/collections/{$col['slug']}`);";
            $lines[] = "  const json = await res.json();";
            $lines[] = "  return json.data ?? json;";
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function getDockerfile(): string
    {
        return <<<'DOCKERFILE'
# ── Stage 1: dependencies ──────────────────────────────────────────────────────
FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci --legacy-peer-deps

# ── Stage 2: builder ───────────────────────────────────────────────────────────
FROM node:20-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

# ── Stage 3: runner ────────────────────────────────────────────────────────────
FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
EXPOSE 3000
ENV PORT=3000
CMD ["node", "server.js"]
DOCKERFILE;
    }
}
